version: '3.9'
services:
  postgres:
    image: postgres
    hostname: localhost
    ports:
      - '0000:5432'
    env_file:
      - path: .env
    environment:
      - POSTGRES_DB=songs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data

  client:
    build: client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/app
      - /usr/app/build
      - /usr/app/node_modules
  
  event-bus:
    build: event-bus
    volumes:
      - ./event-bus:/usr/app
      - /usr/app/node_modules
  
  query:
    build: query
    ports:
      - '0:4002'
    volumes:
      - ./query:/usr/app
      - /usr/app/node_modules
  
  modes:
    build: modes
    ports:
      - '0:4003'
    volumes:
      - ./modes:/usr/app
      - /usr/app/node_modules