services:
  client:
    build: client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/app
      - /usr/app/build
      - /usr/app/node_modules
    networks:
      - orbitus-v222

  query:
    build: query
    ports:
      - "4002:4002"
    environment:
      - SONG_DATABASE_URL=$SONG_DATABASE_URL
      - SONG_PULSE_API_KEY=$SONG_PULSE_API_KEY
      - BUCKET_NAME=$BUCKET_NAME
      - BUCKET_REGION=$BUCKET_REGION
      - CLOUDFRONT_KEY_PAIR_ID=$CLOUDFRONT_KEY_PAIR_ID
      - CLOUDFRONT_PRIVATE_KEY=$CLOUDFRONT_PRIVATE_KEY
    volumes:
      - ./query:/usr/app
      - /usr/app/node_modules
    networks:
      - orbitus-v222

  modes:
    build: modes
    ports:
      - "4003:4003"
    environment:
      - MODE_DATABASE_URL=$MODE_DATABASE_URL
      - MODE_PULSE_API_KEY=$MODE_PULSE_API_KEY
    volumes:
      - ./modes:/usr/app
      - /usr/app/node_modules
    networks:
      - orbitus-v222

  event-bus:
    build: event-bus
    ports:
      - "4005:4005"
    volumes:
      - ./event-bus:/usr/app
      - /usr/app/node_modules
    networks:
      - orbitus-v222

networks:
  orbitus-v222:
    driver: bridge
